### ISSUE TITLE
Ane packaging

### ISSUE THREAD

**Issue by mumeka** [tuarua/Android-ANE-Dependencies#2]
Hello I try to write a admob ane myself for my personal use. However android studio does not package com.google.android.gms:play-services-ads:15.0.0 and com.android.support:appcompat-v7:27.1.0 in the aar file when packaging library. How do you make this process? can you tell a bit if you have time. I have done setvolumeane example by adobe. But it wasnt using different dependencies. Thank you.

**Comment by tuarua** [comment]
It is normal that the aar doesn't include the other dependencies. That's how Android libraries work.

There are 2 ways to include the dependencies
1) download all the aars of the all dependencies and package their .jars and res with adt and platform.xml
2) build an ANE which contains these packages using a script

1) is very very laborious
2) is what this GitHub repo offers.

Have you read this section?
https://github.com/tuarua/Android-ANE-Dependencies#compiling-your-own-libaries

Have a look at my entry for ads-lite and see how it relates to the maven package
https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads-lite/15.0.1
https://github.com/tuarua/Android-ANE-Dependencies/blob/master/build/scripts/packages.xml#L563

Note:  I don't include "play-services-basement" as this is part of play-services-base, a separate package,

You don't need to build appcompat. It is already available here:
https://github.com/tuarua/Android-ANE-Dependencies/blob/master/anes/support/com.android.support.appcompat-v7-27.1.0.ane

**Comment by tuarua** [comment]
Here is the maven page for play-services-ads
 https://mvnrepository.com/artifact/com.google.android.gms/play-services-ads/15.0.0

Note the child dependencies you would also need to include

**Comment by tuarua** [comment]
> AND
ANES for child dependencies

You would normally package the children with the main dependency - to create a neat bundle.
eg play-services-ads you would include, play-services-ads-identifier, -lite, -base

Beware packaging the same child in different ANEs yo uuse. That will cause build errors.

The easiest is just to grab an existing from I or Distriqt - if it's the exact one you need.
I name mine the same as they appear in Android Studio - so is easy to match.
Distriqt name theirs according to their product.

**Comment by mumeka** [comment]
Ok I will work on this and let you know about results, thank you very much for your help.
